// Persona definitions for the strict batch-of-10 audit.
//
// Field strings are written as a real user would phrase the answer in the
// chat UI — including non-English phrasing for personas whose primary
// language is not English. Extraction is the AI's responsibility; if it
// fails on a non-English answer that's a real product gap, not a test gap.

export interface Persona {
  slug: string
  name: string
  route: string
  expectedPurpose: "study" | "work" | "digital_nomad" | "settle"
  expectedDestination: string
  expectedCity: string
  expectedCitizenship: string
  expectedHomeCurrency: string
  expectedDestinationCurrency: string
  expectedFamilyShape: "solo" | "spouse" | "partner" | "family_with_kids"
  fields: Record<string, string>
  expectedProfile: Record<string, string>
  branchSpecificKeys: string[]
}

export const PERSONAS: Persona[] = [
  {
    slug: "01-luciana-br-tokyo-study",
    name: "Luciana",
    route: "Brazilian -> Tokyo (study, solo)",
    expectedPurpose: "study",
    expectedDestination: "Japan",
    expectedCity: "Tokyo",
    expectedCitizenship: "Brazilian",
    expectedHomeCurrency: "BRL",
    expectedDestinationCurrency: "JPY",
    expectedFamilyShape: "solo",
    branchSpecificKeys: ["study_type", "study_field", "study_funding"],
    fields: {
      name: "Meu nome é Luciana.",
      destination: "Quero me mudar para o Japão.",
      target_city: "A cidade é Tóquio (Tokyo).",
      purpose: "Vou estudar um mestrado.",
      visa_role: "Sou a candidata principal.",
      timeline: "Em abril de 2027.",
      citizenship: "Sou brasileira, passaporte do Brasil.",
      moving_alone: "Sim, vou sozinha.",
      duration: "Dois anos.",
      study_type: "Programa de mestrado em universidade.",
      study_field: "Engenharia robótica.",
      study_funding: "Tenho bolsa MEXT do governo japonês.",
      savings_available: "Tenho cerca de 8000 dólares guardados.",
      monthly_budget: "Cerca de 150000 ienes por mês.",
      need_budget_help: "Sim, uma ajuda leve com o orçamento seria boa.",
      current_location: "Moro em São Paulo, Brasil.",
      language_skill: "Meu japonês é mais ou menos N4.",
      education_level: "Bacharelado em engenharia mecânica.",
      prior_visa: "Nunca tive visto japonês.",
      visa_rejections: "Nenhuma rejeição.",
      healthcare_needs: "Não tenho necessidades médicas especiais.",
      pets: "Não tenho pets.",
      special_requirements: "Nada especial.",
    },
    expectedProfile: {
      name: "Luciana",
      destination: "Japan",
      target_city: "Tokyo",
      purpose: "study",
      visa_role: "primary",
      citizenship: "Brazilian",
      study_type: "university",
      study_field: "robot",
      study_funding: "MEXT",
      moving_alone: "yes",
      current_location: "Sao Paulo",
    },
  },
  {
    slug: "02-jake-us-lisbon-nomad",
    name: "Jake",
    route: "American -> Lisbon (digital nomad, solo)",
    expectedPurpose: "digital_nomad",
    expectedDestination: "Portugal",
    expectedCity: "Lisbon",
    expectedCitizenship: "American",
    expectedHomeCurrency: "USD",
    expectedDestinationCurrency: "EUR",
    expectedFamilyShape: "solo",
    branchSpecificKeys: ["remote_income", "income_source", "monthly_income", "income_consistency"],
    fields: {
      name: "I'm Jake.",
      destination: "Portugal.",
      target_city: "Lisbon.",
      purpose: "I'm moving as a digital nomad.",
      visa_role: "Primary applicant.",
      timeline: "In about two months.",
      citizenship: "American, US passport.",
      moving_alone: "Yep, solo — it's just me.",
      duration: "One to two years.",
      remote_income: "Yes, I earn remote income.",
      income_source: "Freelance web development for US clients.",
      monthly_income: "About 6000 dollars a month.",
      income_consistency: "Pretty stable month to month.",
      income_history_months: "I've done this for around three years now.",
      savings_available: "Roughly 25000 dollars saved.",
      monthly_budget: "About 2000 euros per month.",
      need_budget_help: "No, I already planned that part.",
      current_location: "Austin, Texas, USA.",
      language_skill: "No Portuguese yet.",
      education_level: "Bachelor's in computer science.",
      prior_visa: "No Portuguese visa before.",
      visa_rejections: "Never been rejected.",
      healthcare_needs: "None.",
      pets: "No pets.",
      special_requirements: "Nothing special.",
    },
    expectedProfile: {
      name: "Jake",
      destination: "Portugal",
      target_city: "Lisbon",
      purpose: "digital_nomad",
      visa_role: "primary",
      citizenship: "American",
      remote_income: "yes",
      income_source: "freelance",
      monthly_income: "6000",
      income_consistency: "stable",
      current_location: "Austin",
    },
  },
  {
    slug: "03-margaret-uk-barcelona-settle",
    name: "Margaret",
    route: "British -> Barcelona (settle/retire, spouse)",
    expectedPurpose: "settle",
    expectedDestination: "Spain",
    expectedCity: "Barcelona",
    expectedCitizenship: "British",
    expectedHomeCurrency: "GBP",
    expectedDestinationCurrency: "EUR",
    expectedFamilyShape: "spouse",
    branchSpecificKeys: ["settlement_reason", "family_ties", "spouse_joining"],
    fields: {
      name: "I'm Margaret.",
      destination: "Spain.",
      target_city: "Barcelona.",
      purpose: "I want to settle there permanently for retirement.",
      visa_role: "I'm the primary applicant.",
      timeline: "In around six months.",
      citizenship: "British.",
      moving_alone: "No, my husband is coming with me.",
      duration: "Permanently.",
      settlement_reason: "Retirement and lifestyle change.",
      family_ties: "No close family there, but we have friends in Barcelona.",
      spouse_joining: "Yes, my husband is joining.",
      children_count: "No dependent children.",
      savings_available: "About two hundred thousand pounds in savings and pension funds.",
      monthly_budget: "Around 3000 euros a month.",
      need_budget_help: "No, our finances are planned.",
      current_location: "Manchester, United Kingdom.",
      language_skill: "Basic Spanish, around A2.",
      education_level: "Bachelor's degree.",
      prior_visa: "No Spanish visa before.",
      visa_rejections: "No rejections.",
      healthcare_needs: "My husband needs regular blood pressure medication.",
      pets: "We have a cat coming with us.",
      special_requirements: "We need pet-friendly housing.",
    },
    expectedProfile: {
      name: "Margaret",
      destination: "Spain",
      target_city: "Barcelona",
      purpose: "settle",
      visa_role: "primary",
      citizenship: "British",
      moving_alone: "no",
      spouse_joining: "yes",
      settlement_reason: "retirement",
      pets: "cat",
    },
  },
  {
    slug: "04-rajesh-in-toronto-work-family",
    name: "Rajesh",
    route: "Indian -> Toronto (work, family with children)",
    expectedPurpose: "work",
    expectedDestination: "Canada",
    expectedCity: "Toronto",
    expectedCitizenship: "Indian",
    expectedHomeCurrency: "INR",
    expectedDestinationCurrency: "CAD",
    expectedFamilyShape: "family_with_kids",
    branchSpecificKeys: ["job_offer", "job_field", "employer_sponsorship", "highly_skilled", "years_experience", "children_count"],
    fields: {
      name: "My name is Rajesh.",
      destination: "Canada.",
      target_city: "Toronto.",
      purpose: "I'm relocating for work.",
      visa_role: "I'm the primary applicant.",
      timeline: "In about five months.",
      citizenship: "Indian.",
      moving_alone: "No, I'm moving with my family.",
      duration: "Planning permanent residence eventually.",
      job_offer: "Yes, I already have a job offer from a bank in Toronto.",
      job_field: "Data science and analytics.",
      employer_sponsorship: "Yes, the employer is sponsoring through LMIA.",
      highly_skilled: "Yes.",
      years_experience: "Twelve years.",
      spouse_joining: "Yes, my wife is coming too.",
      children_count: "Two children.",
      children_ages: "Eight and five years old.",
      savings_available: "About forty thousand US dollars saved.",
      monthly_budget: "Around 5000 Canadian dollars per month.",
      need_budget_help: "Some help would be useful for Toronto costs.",
      current_location: "Bangalore, India.",
      language_skill: "Fluent in English.",
      education_level: "Master's in statistics.",
      prior_visa: "I had a US tourist visa before.",
      visa_rejections: "No rejections.",
      healthcare_needs: "My younger child has mild asthma.",
      pets: "No pets.",
      special_requirements: "We need good schools nearby.",
    },
    expectedProfile: {
      name: "Rajesh",
      destination: "Canada",
      target_city: "Toronto",
      purpose: "work",
      visa_role: "primary",
      citizenship: "Indian",
      moving_alone: "no",
      job_offer: "yes",
      job_field: "data",
      employer_sponsorship: "yes",
      children_count: "2",
    },
  },
  {
    slug: "05-wei-cn-paris-study",
    name: "Wei",
    route: "Chinese -> Paris (study/PhD, solo)",
    expectedPurpose: "study",
    expectedDestination: "France",
    expectedCity: "Paris",
    expectedCitizenship: "Chinese",
    expectedHomeCurrency: "CNY",
    expectedDestinationCurrency: "EUR",
    expectedFamilyShape: "solo",
    branchSpecificKeys: ["study_type", "study_field", "study_funding"],
    fields: {
      name: "My name is Wei (我叫魏).",
      destination: "I want to move to France.",
      target_city: "Paris.",
      purpose: "I am going to do a PhD.",
      visa_role: "I am the primary applicant.",
      timeline: "September of this year.",
      citizenship: "I am a Chinese citizen.",
      moving_alone: "Yes, just me.",
      duration: "Three to four years.",
      study_type: "University PhD program.",
      study_field: "Molecular biology.",
      study_funding: "I have a university research fellowship.",
      savings_available: "Around ten thousand euros saved.",
      monthly_budget: "Around twelve hundred euros per month.",
      need_budget_help: "Yes, please help me budget.",
      current_location: "Beijing, China.",
      language_skill: "French B1.",
      education_level: "Master's degree in biology.",
      prior_visa: "No French visa before, but I had a UK student visa.",
      visa_rejections: "No rejections.",
      healthcare_needs: "None.",
      pets: "No pets.",
      special_requirements: "Nothing special.",
    },
    expectedProfile: {
      name: "Wei",
      destination: "France",
      target_city: "Paris",
      purpose: "study",
      visa_role: "primary",
      citizenship: "Chinese",
      study_type: "university",
      study_field: "biology",
      study_funding: "fellowship",
      current_location: "Beijing",
    },
  },
  {
    slug: "06-thandi-za-amsterdam-work",
    name: "Thandi",
    route: "South African -> Amsterdam (work, partner)",
    expectedPurpose: "work",
    expectedDestination: "Netherlands",
    expectedCity: "Amsterdam",
    expectedCitizenship: "South African",
    expectedHomeCurrency: "ZAR",
    expectedDestinationCurrency: "EUR",
    expectedFamilyShape: "partner",
    branchSpecificKeys: ["job_offer", "job_field", "employer_sponsorship", "highly_skilled", "spouse_joining"],
    fields: {
      name: "I'm Thandi.",
      destination: "The Netherlands.",
      target_city: "Amsterdam.",
      purpose: "I'm moving for work.",
      visa_role: "Primary applicant.",
      timeline: "In around three months.",
      citizenship: "South African.",
      moving_alone: "No, my partner is joining me.",
      duration: "At least three years.",
      job_offer: "Yes, I have an offer from a tech startup.",
      job_field: "Product management.",
      employer_sponsorship: "Yes, they are sponsoring the visa.",
      highly_skilled: "Yes.",
      years_experience: "Nine years.",
      spouse_joining: "Yes, my partner is coming.",
      children_count: "No children.",
      savings_available: "About twenty thousand euros.",
      monthly_budget: "Around 3200 euros per month.",
      need_budget_help: "No thanks.",
      current_location: "Cape Town, South Africa.",
      language_skill: "English fluent, Dutch beginner.",
      education_level: "Bachelor's in business science.",
      prior_visa: "No Dutch visa before.",
      visa_rejections: "No rejections.",
      healthcare_needs: "None.",
      pets: "No pets.",
      special_requirements: "We'd prefer housing close to transit.",
    },
    expectedProfile: {
      name: "Thandi",
      destination: "Netherlands",
      target_city: "Amsterdam",
      purpose: "work",
      visa_role: "primary",
      citizenship: "South African",
      moving_alone: "no",
      spouse_joining: "yes",
      job_field: "product",
      employer_sponsorship: "yes",
    },
  },
  {
    slug: "07-mateo-ar-rome-settle",
    name: "Mateo",
    route: "Argentinian -> Rome (settle, solo)",
    expectedPurpose: "settle",
    expectedDestination: "Italy",
    expectedCity: "Rome",
    expectedCitizenship: "Argentinian",
    expectedHomeCurrency: "ARS",
    expectedDestinationCurrency: "EUR",
    expectedFamilyShape: "solo",
    branchSpecificKeys: ["settlement_reason", "family_ties"],
    fields: {
      name: "Me llamo Mateo.",
      destination: "Italia.",
      target_city: "Roma.",
      purpose: "Quiero mudarme para establecerme definitivamente.",
      visa_role: "Soy el solicitante principal.",
      timeline: "En unos tres meses.",
      citizenship: "Soy argentino.",
      moving_alone: "Sí, voy solo.",
      duration: "Permanentemente.",
      settlement_reason: "Ciudadanía por ascendencia italiana.",
      family_ties: "Sí, tengo primos en Roma.",
      savings_available: "Tengo unos quince mil euros.",
      monthly_budget: "Alrededor de 1800 euros por mes.",
      need_budget_help: "Un poco de ayuda estaría bien.",
      current_location: "Buenos Aires, Argentina.",
      language_skill: "Italiano intermedio, nivel B1.",
      education_level: "Licenciatura en arquitectura.",
      prior_visa: "No tuve visa italiana antes.",
      visa_rejections: "Nunca me rechazaron.",
      healthcare_needs: "Ninguna.",
      pets: "No tengo mascotas.",
      special_requirements: "Nada especial.",
    },
    expectedProfile: {
      name: "Mateo",
      destination: "Italy",
      target_city: "Rome",
      purpose: "settle",
      visa_role: "primary",
      citizenship: "Argentinian",
      settlement_reason: "ancestry",
      family_ties: "yes",
      moving_alone: "yes",
      current_location: "Buenos Aires",
    },
  },
  {
    slug: "08-amira-eg-london-study",
    name: "Amira",
    route: "Egyptian -> London (study, solo)",
    expectedPurpose: "study",
    expectedDestination: "United Kingdom",
    expectedCity: "London",
    expectedCitizenship: "Egyptian",
    expectedHomeCurrency: "EGP",
    expectedDestinationCurrency: "GBP",
    expectedFamilyShape: "solo",
    branchSpecificKeys: ["study_type", "study_field", "study_funding"],
    fields: {
      name: "I'm Amira (أنا أميرة).",
      destination: "I want to move to the United Kingdom.",
      target_city: "London.",
      purpose: "I'd like to do a master's in international law.",
      visa_role: "I'm the primary applicant.",
      timeline: "September of this year.",
      citizenship: "Egyptian.",
      moving_alone: "Yes, on my own.",
      duration: "One year.",
      study_type: "Master's degree at a university.",
      study_field: "International law.",
      study_funding: "Self-funded with family support.",
      savings_available: "About thirty thousand pounds including family support.",
      monthly_budget: "Around fifteen hundred pounds monthly.",
      need_budget_help: "Yes please, London is expensive.",
      current_location: "Cairo, Egypt.",
      language_skill: "Fluent English.",
      education_level: "Bachelor's in law.",
      prior_visa: "I had a UK tourist visa before.",
      visa_rejections: "No rejections.",
      healthcare_needs: "None.",
      pets: "No pets.",
      special_requirements: "Nothing special.",
    },
    expectedProfile: {
      name: "Amira",
      destination: "United Kingdom",
      target_city: "London",
      purpose: "study",
      visa_role: "primary",
      citizenship: "Egyptian",
      study_type: "university",
      study_field: "law",
      study_funding: "family",
      current_location: "Cairo",
    },
  },
  {
    slug: "09-hassan-pk-sydney-work-family",
    name: "Hassan",
    route: "Pakistani -> Sydney (work, spouse + child)",
    expectedPurpose: "work",
    expectedDestination: "Australia",
    expectedCity: "Sydney",
    expectedCitizenship: "Pakistani",
    expectedHomeCurrency: "PKR",
    expectedDestinationCurrency: "AUD",
    expectedFamilyShape: "family_with_kids",
    branchSpecificKeys: ["job_offer", "job_field", "employer_sponsorship", "highly_skilled", "spouse_joining", "children_count"],
    fields: {
      name: "My name is Hassan (میرا نام حسن ہے).",
      destination: "Australia.",
      target_city: "Sydney.",
      purpose: "I'm relocating for work.",
      visa_role: "I'm the primary applicant.",
      timeline: "In about four months.",
      citizenship: "Pakistani.",
      moving_alone: "No, my wife and son are joining me.",
      duration: "Permanently, aiming for PR.",
      job_offer: "Yes, a hospital has offered me a position.",
      job_field: "Cardiology — I'm a doctor.",
      employer_sponsorship: "Yes, the hospital is sponsoring my visa.",
      highly_skilled: "Yes, I'm a specialist doctor.",
      years_experience: "Ten years.",
      spouse_joining: "Yes, my wife is coming.",
      children_count: "One child.",
      children_ages: "Three years old.",
      savings_available: "About fifty thousand Australian dollars.",
      monthly_budget: "Around six thousand Australian dollars monthly.",
      need_budget_help: "No, we've planned it.",
      current_location: "Lahore, Pakistan.",
      language_skill: "Fluent English.",
      education_level: "MBBS and cardiology fellowship.",
      prior_visa: "Had Australian tourist visa before.",
      visa_rejections: "No rejections.",
      healthcare_needs: "None for us.",
      pets: "No pets.",
      special_requirements: "Need daycare near the hospital.",
    },
    expectedProfile: {
      name: "Hassan",
      destination: "Australia",
      target_city: "Sydney",
      purpose: "work",
      visa_role: "primary",
      citizenship: "Pakistani",
      moving_alone: "no",
      spouse_joining: "yes",
      children_count: "1",
      job_field: "cardiology",
      employer_sponsorship: "yes",
    },
  },
  {
    slug: "10-chika-ng-berlin-work",
    name: "Chika",
    route: "Nigerian -> Berlin (work, solo)",
    expectedPurpose: "work",
    expectedDestination: "Germany",
    expectedCity: "Berlin",
    expectedCitizenship: "Nigerian",
    expectedHomeCurrency: "NGN",
    expectedDestinationCurrency: "EUR",
    expectedFamilyShape: "solo",
    branchSpecificKeys: ["job_offer", "job_field", "employer_sponsorship", "highly_skilled"],
    fields: {
      name: "I'm Chika.",
      destination: "Germany.",
      target_city: "Berlin.",
      purpose: "I'm moving to take up a job.",
      visa_role: "Primary applicant.",
      timeline: "In around three months.",
      citizenship: "Nigerian.",
      moving_alone: "Yes, solo for now.",
      duration: "Long term, hoping for a Blue Card.",
      job_offer: "Yes, I have a signed offer from a software company in Berlin.",
      job_field: "Software engineering, backend.",
      employer_sponsorship: "Yes, they are sponsoring my EU Blue Card.",
      highly_skilled: "Yes.",
      years_experience: "Seven years of professional experience.",
      savings_available: "Around 12000 euros saved up.",
      monthly_budget: "About 2200 euros per month including rent.",
      need_budget_help: "Yes, some help with Berlin numbers please.",
      current_location: "Lagos, Nigeria.",
      language_skill: "English native, German A1.",
      education_level: "Bachelor's in computer science.",
      prior_visa: "I had a Schengen tourist visa once.",
      visa_rejections: "No rejections.",
      healthcare_needs: "None.",
      pets: "No pets.",
      special_requirements: "Looking for help with the Anmeldung process after arrival.",
    },
    expectedProfile: {
      name: "Chika",
      destination: "Germany",
      target_city: "Berlin",
      purpose: "work",
      visa_role: "primary",
      citizenship: "Nigerian",
      moving_alone: "yes",
      job_offer: "yes",
      job_field: "software",
      employer_sponsorship: "yes",
      current_location: "Lagos",
    },
  },
]
