// =============================================================
  // @workspace/agents — Wave 2.0 intake-field registry (snapshot)
  // =============================================================
  // Snapshot of the field schema GoMate uses for the relocation
  // interview. Source of truth lives in
  //   artifacts/gomate/src/lib/gomate/profile-schema.ts
  // (~1700 lines, includes Zod schema + extractionHints + required
  // predicates + dependsOn gating). The Wave 2.0 Extractor agent
  // only needs label + intent + type, so this module ships a thin
  // snapshot rather than importing across the artifact/lib boundary
  // (which would invert the workspace dependency direction).
  //
  // TODO[wave-2.x-unify-schema]: promote profile-schema.ts to a
  // shared workspace package (e.g. @workspace/intake-schema) and
  // have both lib/agents/ and artifacts/gomate/ consume it. Until
  // then, keep field keys + labels in sync by regenerating this
  // file from profile-schema.ts (see scripts/regen-intake-fields.ts
  // in a future wave, or the inline generator in commit history).
  //
  // This file was generated mechanically — do not hand-edit field
  // keys or labels; edit profile-schema.ts and regenerate.
  // =============================================================

  export const ALL_FIELDS = [
    "name",
  "citizenship",
  "other_citizenships",
  "birth_year",
  "current_location",
  "destination",
  "target_city",
  "purpose",
  "visa_role",
  "partner_citizenship",
  "partner_visa_status",
  "relationship_type",
  "partner_residency_duration",
  "relationship_duration",
  "duration",
  "timeline",
  "study_type",
  "study_field",
  "study_funding",
  "job_offer",
  "job_field",
  "employer_sponsorship",
  "highly_skilled",
  "remote_income",
  "income_source",
  "monthly_income",
  "income_consistency",
  "income_history_months",
  "settlement_reason",
  "family_ties",
  "moving_alone",
  "spouse_joining",
  "children_count",
  "children_ages",
  "savings_available",
  "monthly_budget",
  "preferred_currency",
  "need_budget_help",
  "language_skill",
  "education_level",
  "years_experience",
  "prior_visa",
  "visa_rejections",
  "healthcare_needs",
  "pets",
  "special_requirements",
  "posting_or_secondment",
  "home_country_employer",
  "posting_employer_address",
  "posting_duration_months",
  "a1_certificate_status",
  "coc_status",
  "pwd_filed",
  "prior_visa_country",
  "prior_visa_type",
  "prior_residence_outside_origin",
  "birth_certificate_apostille_status",
  "marriage_certificate_apostille_status",
  "diploma_apostille_status",
  "police_clearance_status",
  "medical_exam_required",
  "spouse_career_field",
  "spouse_seeking_work",
  "spouse_language_skills",
  "spouse_visa_dependency",
  "children_school_type_preference",
  "children_language_skills_destination",
  "children_special_needs",
  "children_birth_certificate_apostille_status",
  "chronic_condition_description",
  "prescription_medications",
  "english_speaking_doctor_required",
  "prescription_medications_list",
  "pre_existing_condition_disclosure_concern",
  "pet_microchip_status",
  "pet_vaccination_status",
  "pet_size_weight",
  "pet_breed",
  "pet_age",
  "bringing_vehicle",
  "vehicle_make_model_year",
  "vehicle_origin_country",
  "vehicle_emission_standard",
  "home_purchase_intent",
  "rental_budget_max",
  "furnished_preference",
  "commute_tolerance_minutes",
  "accessibility_needs",
  "departure_tax_filing_required",
  "exit_tax_obligations",
  "pension_continuity_required",
  "bringing_personal_effects",
  "estimated_goods_volume_cubic_meters",
  "goods_shipping_method",
  "need_storage",
  "origin_lease_status",
  "origin_lease_termination_notice_days",
  "driver_license_origin",
  "driver_license_destination_intent",
  "working_remote_during_transition",
  "religious_practice_required",
  "register_with_origin_embassy_intent",
  "emergency_contact_origin_name",
  "emergency_contact_origin_phone",
  "pre_existing_investments_to_migrate",
  "existing_offshore_accounts",
  "insurance_needs_household",
  "insurance_needs_vehicle",
  "insurance_needs_life",
  "gap_insurance_needed",
  "family_visa_cascade_aware",
  ] as const;

  export type AllFieldKey = (typeof ALL_FIELDS)[number];

  export type FieldType = "string" | "number" | "yes_no";

  export interface FieldConfig {
    key: AllFieldKey;
    label: string;
    intent: string;
    type: FieldType;
  }

  export const FIELD_INFO: Record<AllFieldKey, FieldConfig> = {
    name: { key: "name", label: "Name", intent: "User's name for personalization", type: "string" },
  citizenship: { key: "citizenship", label: "Citizenship", intent: "Passport/nationality for visa eligibility", type: "string" },
  other_citizenships: { key: "other_citizenships", label: "Other Citizenships", intent: "Dual/multiple passports that may unlock additional visa pathways", type: "string" },
  birth_year: { key: "birth_year", label: "Birth Year", intent: "Age for age-restricted visas (Working Holiday 18-30/35, retirement 50+)", type: "number" },
  current_location: { key: "current_location", label: "Current Location", intent: "Where user currently lives for consulate routing", type: "string" },
  destination: { key: "destination", label: "Destination Country", intent: "Target country for relocation", type: "string" },
  target_city: { key: "target_city", label: "Target City", intent: "Specific city for housing and cost of living info", type: "string" },
  purpose: { key: "purpose", label: "Purpose", intent: "Primary reason: study, work, settle, digital nomad", type: "string" },
  visa_role: { key: "visa_role", label: "Visa Role", intent: "Whether user is the primary visa applicant or joining someone else (dependent)", type: "string" },
  partner_citizenship: { key: "partner_citizenship", label: "Partner's Citizenship", intent: "Citizenship/nationality of the partner or sponsor", type: "string" },
  partner_visa_status: { key: "partner_visa_status", label: "Partner's Visa/Residency Status", intent: "What visa or residency status the partner holds", type: "string" },
  relationship_type: { key: "relationship_type", label: "Relationship Type", intent: "Type of relationship with partner/sponsor", type: "string" },
  partner_residency_duration: { key: "partner_residency_duration", label: "Partner's Time in Country", intent: "How long partner has been living in destination", type: "number" },
  relationship_duration: { key: "relationship_duration", label: "Relationship Duration", intent: "How long in the relationship (some visas require proof)", type: "number" },
  duration: { key: "duration", label: "Duration", intent: "Intended length of stay", type: "string" },
  timeline: { key: "timeline", label: "Timeline", intent: "When user plans to move", type: "string" },
  study_type: { key: "study_type", label: "Type of Study", intent: "University, language school, vocational, or exchange program", type: "string" },
  study_field: { key: "study_field", label: "Field of Study", intent: "Academic field or subject area", type: "string" },
  study_funding: { key: "study_funding", label: "Study Funding", intent: "How studies will be funded", type: "string" },
  job_offer: { key: "job_offer", label: "Job Offer Status", intent: "Whether user has a job offer", type: "yes_no" },
  job_field: { key: "job_field", label: "Job Field", intent: "Industry or profession", type: "string" },
  employer_sponsorship: { key: "employer_sponsorship", label: "Employer Sponsorship", intent: "Whether employer will sponsor visa", type: "yes_no" },
  highly_skilled: { key: "highly_skilled", label: "Highly Skilled Professional", intent: "Eligibility for skilled worker visa programs", type: "yes_no" },
  remote_income: { key: "remote_income", label: "Remote Income", intent: "Whether user has remote income", type: "yes_no" },
  income_source: { key: "income_source", label: "Income Source", intent: "Type of remote work", type: "string" },
  monthly_income: { key: "monthly_income", label: "Monthly Income", intent: "Income level for digital nomad visa requirements (include currency, e.g. '5000 USD')", type: "string" },
  income_consistency: { key: "income_consistency", label: "Income Consistency", intent: "How stable/consistent the income is - important for DN visa proof", type: "string" },
  income_history_months: { key: "income_history_months", label: "Income History", intent: "How long user has had this income - many DN visas require 6-12 months proof", type: "number" },
  settlement_reason: { key: "settlement_reason", label: "Settlement Reason", intent: "Specific reason for permanent settlement", type: "string" },
  family_ties: { key: "family_ties", label: "Family Ties", intent: "Existing family connections in destination", type: "yes_no" },
  moving_alone: { key: "moving_alone", label: "Moving Alone", intent: "Whether relocating solo or with others", type: "yes_no" },
  spouse_joining: { key: "spouse_joining", label: "Spouse Joining", intent: "Whether partner/spouse is relocating too", type: "yes_no" },
  children_count: { key: "children_count", label: "Number of Children", intent: "How many children are relocating", type: "number" },
  children_ages: { key: "children_ages", label: "Children's Ages", intent: "Ages for school planning", type: "string" },
  savings_available: { key: "savings_available", label: "Available Savings", intent: "Total savings for relocation (include currency, e.g. '45000 EUR')", type: "string" },
  monthly_budget: { key: "monthly_budget", label: "Monthly Budget", intent: "Expected monthly spending (include currency, e.g. '2500 EUR')", type: "string" },
  preferred_currency: { key: "preferred_currency", label: "Preferred Currency", intent: "Currency the user wants all amounts displayed in", type: "string" },
  need_budget_help: { key: "need_budget_help", label: "Budget Help Needed", intent: "Whether user needs help with budgeting", type: "yes_no" },
  language_skill: { key: "language_skill", label: "Language Skills", intent: "Proficiency in destination language", type: "string" },
  education_level: { key: "education_level", label: "Education Level", intent: "Highest qualification achieved", type: "string" },
  years_experience: { key: "years_experience", label: "Work Experience", intent: "Years of professional experience", type: "number" },
  prior_visa: { key: "prior_visa", label: "Prior Visa History", intent: "Previous visas for destination country", type: "yes_no" },
  visa_rejections: { key: "visa_rejections", label: "Visa Rejections", intent: "Any previous visa rejections", type: "yes_no" },
  healthcare_needs: { key: "healthcare_needs", label: "Healthcare Needs", intent: "Medical requirements and conditions", type: "string" },
  pets: { key: "pets", label: "Pets", intent: "Animals relocating with user", type: "string" },
  special_requirements: { key: "special_requirements", label: "Special Requirements", intent: "Any other special considerations", type: "string" },
  posting_or_secondment: { key: "posting_or_secondment", label: "Corporate Posting / Secondment", intent: "Whether the move is a corporate posting from the user's current employer (triggers A1/CoC/PWD obligations)", type: "yes_no" },
  home_country_employer: { key: "home_country_employer", label: "Home Country Employer", intent: "Employer name in origin country (required for posted worker declarations)", type: "string" },
  posting_employer_address: { key: "posting_employer_address", label: "Posting Employer Address", intent: "Home country employer's registered address (for posted worker declarations and A1 certificate)", type: "string" },
  posting_duration_months: { key: "posting_duration_months", label: "Posting Duration (Months)", intent: "Length of the posting in months (max 24 months for EU A1 certificate)", type: "number" },
  a1_certificate_status: { key: "a1_certificate_status", label: "A1 Certificate Status", intent: "EU social security continuity certificate (proves home country social security continues during posting; values: not_started | in_progress | obtained | not_applicable)", type: "string" },
  coc_status: { key: "coc_status", label: "Certificate of Coverage Status", intent: "Bilateral social security treaty Certificate of Coverage for non-EU postings (US-Sweden, India-Sweden, etc.; values: not_started | in_progress | obtained | not_applicable)", type: "string" },
  pwd_filed: { key: "pwd_filed", label: "Posted Worker Declaration Filed", intent: "Posted Worker Declaration filed with destination labor authority (Arbetsmiljöverket in Sweden, ZOLL in Germany) — must be filed before work starts", type: "yes_no" },
  prior_visa_country: { key: "prior_visa_country", label: "Prior Visa Country", intent: "Country that issued the prior visa", type: "string" },
  prior_visa_type: { key: "prior_visa_type", label: "Prior Visa Type", intent: "Type/category of the prior visa", type: "string" },
  prior_residence_outside_origin: { key: "prior_residence_outside_origin", label: "Prior Residence Outside Origin", intent: "Countries the user has lived in for 6+ months outside origin (police clearance and immigration history)", type: "yes_no" },
  birth_certificate_apostille_status: { key: "birth_certificate_apostille_status", label: "Birth Certificate Apostille", intent: "Apostille status for the user's birth certificate (values: not_needed | in_progress | obtained)", type: "string" },
  marriage_certificate_apostille_status: { key: "marriage_certificate_apostille_status", label: "Marriage Certificate Apostille", intent: "Apostille status for the user's marriage certificate (values: not_needed | in_progress | obtained) — only when married", type: "string" },
  diploma_apostille_status: { key: "diploma_apostille_status", label: "Diploma Apostille", intent: "Apostille status for academic diplomas (required for skilled visa categories; values: not_needed | in_progress | obtained)", type: "string" },
  police_clearance_status: { key: "police_clearance_status", label: "Police Clearance Status", intent: "Police clearance / criminal background certificate from origin (values: not_needed | applied | obtained)", type: "string" },
  medical_exam_required: { key: "medical_exam_required", label: "Medical Exam Required", intent: "Whether destination + visa type requires a medical exam (DERIVED — not asked directly)", type: "yes_no" },
  spouse_career_field: { key: "spouse_career_field", label: "Spouse's Career Field", intent: "Spouse/partner's career field (for trailing-spouse work permit and labor market matching)", type: "string" },
  spouse_seeking_work: { key: "spouse_seeking_work", label: "Spouse Seeking Work", intent: "Whether spouse intends to seek work in destination (affects dependent work-permit pathway)", type: "string" },
  spouse_language_skills: { key: "spouse_language_skills", label: "Spouse Language Skills", intent: "Spouse's destination-language proficiency (low / medium / high)", type: "string" },
  spouse_visa_dependency: { key: "spouse_visa_dependency", label: "Spouse Visa Dependency", intent: "How spouse's visa derives from primary applicant's (e.g., dependent permit, joining family member)", type: "string" },
  children_school_type_preference: { key: "children_school_type_preference", label: "Children's School Type Preference", intent: "Preferred school type (public / private / international / no_preference)", type: "string" },
  children_language_skills_destination: { key: "children_language_skills_destination", label: "Children's Destination Language Skills", intent: "Children's destination-language proficiency (low / medium / high)", type: "string" },
  children_special_needs: { key: "children_special_needs", label: "Children's Special Needs", intent: "Free-text disclosure of children's special needs (always optional)", type: "string" },
  children_birth_certificate_apostille_status: { key: "children_birth_certificate_apostille_status", label: "Children's Birth Certificate Apostille", intent: "Apostille status for children's birth certificates (required for dependent visa applications; values: not_needed | in_progress | obtained)", type: "string" },
  chronic_condition_description: { key: "chronic_condition_description", label: "Chronic Condition Description", intent: "Free-text description of chronic medical condition (for healthcare continuity planning)", type: "string" },
  prescription_medications: { key: "prescription_medications", label: "Takes Prescription Medications", intent: "Whether user takes prescription medications (some are restricted in destination — Adderall in Japan, codeine in many countries)", type: "string" },
  english_speaking_doctor_required: { key: "english_speaking_doctor_required", label: "English-Speaking Doctor Required", intent: "Whether the user requires an English-speaking doctor in destination", type: "yes_no" },
  prescription_medications_list: { key: "prescription_medications_list", label: "Prescription Medications List", intent: "Free-text list of medications (for restriction checking; e.g. Adderall illegal in Japan, certain CBD in UAE)", type: "string" },
  pre_existing_condition_disclosure_concern: { key: "pre_existing_condition_disclosure_concern", label: "Pre-Existing Condition Disclosure Concern", intent: "Whether user has concerns about disclosing pre-existing conditions for visa/insurance", type: "yes_no" },
  pet_microchip_status: { key: "pet_microchip_status", label: "Pet Microchip Status", intent: "Whether pet has an ISO 11784/11785 compliant microchip (required for most international pet imports)", type: "string" },
  pet_vaccination_status: { key: "pet_vaccination_status", label: "Pet Vaccination Status", intent: "Pet vaccination currency (current / outdated / starting) — rabies and core vaccines", type: "string" },
  pet_size_weight: { key: "pet_size_weight", label: "Pet Size / Weight", intent: "Pet size and weight (cabin vs cargo decisions; size-based housing restrictions)", type: "string" },
  pet_breed: { key: "pet_breed", label: "Pet Breed", intent: "Pet breed (some destinations restrict specific breeds — banned-breed lists)", type: "string" },
  pet_age: { key: "pet_age", label: "Pet Age", intent: "Pet age (travel risk; some carriers restrict by age)", type: "string" },
  bringing_vehicle: { key: "bringing_vehicle", label: "Bringing Vehicle", intent: "Whether the user plans to import a vehicle to the destination (gating question; surfaced contextually by Coordinator)", type: "yes_no" },
  vehicle_make_model_year: { key: "vehicle_make_model_year", label: "Vehicle Make/Model/Year", intent: "Vehicle identification (for import compliance and registration)", type: "string" },
  vehicle_origin_country: { key: "vehicle_origin_country", label: "Vehicle Origin Country", intent: "Where the vehicle is being shipped from (for export/import paperwork)", type: "string" },
  vehicle_emission_standard: { key: "vehicle_emission_standard", label: "Vehicle Emission Standard", intent: "Emission standard (Euro 5/6, EPA Tier, etc.) — for EU import compliance", type: "string" },
  home_purchase_intent: { key: "home_purchase_intent", label: "Home Purchase Intent", intent: "Whether user intends to purchase a home (vs renting) — for mortgage / property tax planning", type: "yes_no" },
  rental_budget_max: { key: "rental_budget_max", label: "Maximum Rental Budget", intent: "Maximum monthly rental budget (include currency, e.g. '1500 EUR') — used by Housing Specialist", type: "string" },
  furnished_preference: { key: "furnished_preference", label: "Furnished Preference", intent: "Preference for furnished, unfurnished, or either (for housing search)", type: "string" },
  commute_tolerance_minutes: { key: "commute_tolerance_minutes", label: "Commute Tolerance (Minutes)", intent: "Maximum acceptable one-way commute in minutes (for housing-vs-workplace location matching)", type: "number" },
  accessibility_needs: { key: "accessibility_needs", label: "Accessibility Needs", intent: "Free-text disclosure of accessibility needs (mobility, sensory, cognitive)", type: "string" },
  departure_tax_filing_required: { key: "departure_tax_filing_required", label: "Departure Tax Filing Required", intent: "Whether origin requires a departure-tax filing (Sweden, US, Norway, Eritrea, etc.) — DERIVED from origin", type: "string" },
  exit_tax_obligations: { key: "exit_tax_obligations", label: "Exit Tax Obligations", intent: "Free-text summary of exit-tax obligations (populated by Tax Strategist agent in later wave)", type: "string" },
  pension_continuity_required: { key: "pension_continuity_required", label: "Pension Continuity Required", intent: "Whether user has pension contributions that need continuity planning (totalization treaties, etc.)", type: "string" },
  bringing_personal_effects: { key: "bringing_personal_effects", label: "Bringing Personal Effects", intent: "Whether the user is shipping personal belongings to the destination (gating; surfaced contextually)", type: "yes_no" },
  estimated_goods_volume_cubic_meters: { key: "estimated_goods_volume_cubic_meters", label: "Estimated Goods Volume (m³)", intent: "Approximate volume of personal effects in cubic meters (for shipping quotes)", type: "number" },
  goods_shipping_method: { key: "goods_shipping_method", label: "Goods Shipping Method", intent: "Preferred shipping method (air_freight | sea_freight | land | self_carry)", type: "string" },
  need_storage: { key: "need_storage", label: "Need Storage", intent: "Whether short-term storage is needed during the transition (between origin lease end and destination move-in)", type: "yes_no" },
  origin_lease_status: { key: "origin_lease_status", label: "Origin Lease Status", intent: "Origin housing status (owning | renting | neither) — for departure timeline", type: "string" },
  origin_lease_termination_notice_days: { key: "origin_lease_termination_notice_days", label: "Origin Lease Termination Notice (Days)", intent: "Days' notice needed to terminate origin lease (typically 30-90) — for Departure Origin Services timeline", type: "number" },
  driver_license_origin: { key: "driver_license_origin", label: "Driver's License (Origin)", intent: "Whether the user holds a driver's license in their origin country (gating; surfaced contextually)", type: "yes_no" },
  driver_license_destination_intent: { key: "driver_license_destination_intent", label: "Destination License Intent", intent: "Plan for destination license (use_existing | exchange | convert | not_driving) — EU mutual recognition vs non-EU conversion paths", type: "string" },
  working_remote_during_transition: { key: "working_remote_during_transition", label: "Working Remote During Transition", intent: "Whether user will work remotely during the move period (affects tax residency rules during transition)", type: "yes_no" },
  religious_practice_required: { key: "religious_practice_required", label: "Religious / Lifestyle Practice", intent: "Free-text disclosure of religious or lifestyle practice (community matching, dietary needs, schooling) — NEVER asked unprompted", type: "string" },
  register_with_origin_embassy_intent: { key: "register_with_origin_embassy_intent", label: "Embassy Registration Intent", intent: "Whether user intends to register with origin embassy (yes | no | already_registered) — NEVER asked unprompted", type: "yes_no" },
  emergency_contact_origin_name: { key: "emergency_contact_origin_name", label: "Emergency Contact (Name)", intent: "Emergency contact name in origin country (always optional)", type: "string" },
  emergency_contact_origin_phone: { key: "emergency_contact_origin_phone", label: "Emergency Contact (Phone)", intent: "Emergency contact phone in origin country (always optional)", type: "string" },
  pre_existing_investments_to_migrate: { key: "pre_existing_investments_to_migrate", label: "Pre-Existing Investments to Migrate", intent: "Whether user has investments needing migration planning — NEVER asked unprompted", type: "yes_no" },
  existing_offshore_accounts: { key: "existing_offshore_accounts", label: "Existing Offshore Accounts", intent: "Whether user holds existing offshore accounts (FBAR/CRS reporting awareness) — NEVER asked unprompted", type: "yes_no" },
  insurance_needs_household: { key: "insurance_needs_household", label: "Household Insurance Needed", intent: "Whether user needs household / contents insurance in destination", type: "yes_no" },
  insurance_needs_vehicle: { key: "insurance_needs_vehicle", label: "Vehicle Insurance Needed", intent: "Whether user needs vehicle insurance (n_a if not bringing vehicle)", type: "yes_no" },
  insurance_needs_life: { key: "insurance_needs_life", label: "Life Insurance Needed", intent: "Whether user needs life insurance review for the move", type: "yes_no" },
  gap_insurance_needed: { key: "gap_insurance_needed", label: "Gap Insurance Needed", intent: "Whether user needs gap insurance (between origin coverage end and destination coverage start)", type: "yes_no" },
  family_visa_cascade_aware: { key: "family_visa_cascade_aware", label: "Family Visa Cascade Awareness", intent: "Whether user understands the primary-then-dependent visa sequence (primary's visa must be approved before dependents apply)", type: "yes_no" },
  };
  