import { Router, type IRouter } from "express";
import healthRouter from "./health";
import agentsHealthRouter from "./agents-health";
import chatRouter from "./chat";
import chatV1Router from "./chat-v1";
import subscriptionRouter from "./subscription";
import profileRouter from "./profile";
import guidesRouter from "./guides";
import documentsRouter from "./documents";
import visaTrackerRouter from "./visa-tracker";
import settlingInRouter from "./settling-in";
import plansRouter from "./plans";
import progressRouter from "./progress";
import checklistProgressRouter from "./checklist-progress";
import accountRouter from "./account";
import chatHistoryRouter from "./chat-history";
import wellbeingRouter from "./wellbeing";
import aiResearchRouter from "./ai-research";
import agentStatusSseRouter from "./agent-status-sse";
import researchDispatchPreviewRouter from "./research-dispatch-preview";
import agentAuditRouter from "./agent-audit";
import costOfLivingRouter from "./cost-of-living";
import preDepartureRouter from "./pre-departure";
import exchangeRateRouter from "./exchange-rate";
import vaultRouter from "./vault";
import readinessRouter from "./readiness";
import risksRouter from "./risks";
import pathwaysRouter from "./pathways";
import arrivalPlaybookRouter from "./arrival-playbook";
import flowsRouter from "./flows";
import licenseInsuranceRouter from "./license-insurance";
import orientationRouter from "./orientation";
import housingSupportRouter from "./housing-support";
import departureFlowRouter from "./departure-flow";
import petRelocationRouter from "./pet-relocation";
import notificationsRouter from "./notifications";
import taxOverviewRouter from "./tax-overview";
import ruleChangesRouter from "./rule-changes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(agentsHealthRouter);
router.use(chatRouter);
router.use(chatV1Router);
router.use(chatHistoryRouter);
router.use(subscriptionRouter);
router.use(profileRouter);
router.use(guidesRouter);
router.use(documentsRouter);
router.use(visaTrackerRouter);
router.use(settlingInRouter);
router.use(plansRouter);
router.use(progressRouter);
router.use(checklistProgressRouter);
router.use(accountRouter);
router.use(wellbeingRouter);
router.use(aiResearchRouter);
router.use(agentStatusSseRouter);
router.use(researchDispatchPreviewRouter);
router.use(agentAuditRouter);
router.use(costOfLivingRouter);
router.use(preDepartureRouter);
router.use(exchangeRateRouter);
router.use(vaultRouter);
router.use(readinessRouter);
router.use(risksRouter);
router.use(pathwaysRouter);
router.use(arrivalPlaybookRouter);
router.use(flowsRouter);
router.use(licenseInsuranceRouter);
router.use(orientationRouter);
router.use(housingSupportRouter);
router.use(departureFlowRouter);
router.use(petRelocationRouter);
router.use(notificationsRouter);
router.use(taxOverviewRouter);
router.use(ruleChangesRouter);

export default router;
